### PR TITLE
Add tests for parsing example file

### PR DESCRIPTION
**Pull request by marcomorain**

### CODE REVIEW

**Comment by marcomorain** [comment]
Hi @bdesham I'm thinking of using clj-plist for a project at CircleCI so I added some basic tests. Would you be able to cut a new release to Clojars with the new `keyword-fn` feature?

thanks!

**Comment by bdesham** [comment]
I'm traveling right now but I'll take a look at this when I get back next week!

**Comment by marcomorain** [comment]
Awesome, thank Ben!

**Comment by bdesham** [comment]
Hi Marc— the new version (0.10.0) is now [available from Clojars](https://clojars.org/com.github.bdesham/clj-plist).

**Comment by marcomorain** [comment]
Hi Ben, I've just opened a PR here, so 0.10.0 should be in production at CircleCI in a few minutes :)

**Pull request merged**
